### PR TITLE
fix division by 0

### PR DESCRIPTION
**Pull request by koma85**

### CODE REVIEW

**Comment by koma85** [comment]
This patch fixes a division by zero.

**Comment by cgagnaire** [comment]
Hi @koma85,
Thanks for the feedback!
However, can you, instead of doing the "+1", set the \*\_prct variable to 0 and then test if the packect_* variables are greater than 0 ?
Thanks again.

**Comment by cgagnaire** [comment]
Or this way its better : 
my $dropped_in_prct = ($packets_in > 0) ? $dropped_in * 100 / $packets_in : 0;

**Comment by koma85** [comment]
I'll try that my $dropped_in_prct = ($packets_in > 0) ? $dropped_in * 100 / $packets_in : 0;
stay tuned

**Comment by koma85** [comment]
I'm closing this pull request because my suggested fix is too weak.
Testing the new proposed fix instead.

**Pull request closed without merging**
